### PR TITLE
MUTES can have no params now for purposes of BEING LAZY

### PR DESCRIPTION
**Pull request by OneTrueBen**
sometimes CERTAIN MODS forget to put time on they mutes. this changes makes the bot decide how much time to mute for

### CODE REVIEW

**Review by benjjs — CHANGES_REQUESTED** [review]
This actively makes the bot worse

**Comment by OneTrueBen** [comment]
> 
> 
> This actively makes the bot worse

what changed do you request

**Review by ARandomCl0wn — DISMISSED** [review]
the solution is to stop being lazy when muting people.

"goka", while very versatile as a phrase, does not really always encompass why people are muted.  if you are going to use a random amount of time for a mute, then i will not approve the request until you also add something where the reason for muting is determined by markov chain involving the last message sent by someone before they were muted

also change line 79.  if you are going to randomly determine the amount of time to mute someone for, the amount shown should not be an emoji

**Comment by OneTrueBen** [comment]
> also change line 79. if you are going to randomly determine the amount of time to mute someone for, the amount shown should not be an emoji

the amount shown is a number. but there is an emoji as well.

**Review by benjjs — CHANGES_REQUESTED** [review]
An hour is too long to mute someone for when you're too lazy to even specify a time. How about a default of 1 minute.

**Comment by OneTrueBen** [comment]
> 
> 
> An hour is too long to mute someone for when you're too lazy to even specify a time. How about a default of 1 minute.

how about 5 minutes

**Review by benjjs — APPROVED** [review]
OK this looks acceptable.

**Pull request merged**
